//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSB_VisiteEntities : DbContext
    {
        public GSB_VisiteEntities()
            : base("name=GSB_VisiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FAMILLE> FAMILLEs { get; set; }
        public DbSet<MEDICAMENT> MEDICAMENTs { get; set; }
        public DbSet<MOTIF_VISITE> MOTIF_VISITE { get; set; }
        public DbSet<OFFRIR> OFFRIRs { get; set; }
        public DbSet<POSSEDER> POSSEDERs { get; set; }
        public DbSet<PRATICIEN> PRATICIENs { get; set; }
        public DbSet<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
        public DbSet<REGION> REGIONs { get; set; }
        public DbSet<SECTEUR> SECTEURs { get; set; }
        public DbSet<SPECIALITE> SPECIALITEs { get; set; }
        public DbSet<TRAVAILLER> TRAVAILLERs { get; set; }
        public DbSet<TYPE_PRATICIEN> TYPE_PRATICIEN { get; set; }
        public DbSet<VISITEUR> VISITEURs { get; set; }
        public DbSet<VAFFECTATION> VAFFECTATION { get; set; }
    }
}
